name: crowdlift
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.1
  confetti: ^0.8.0
  dotenv: ^4.2.0
  email_validator: ^3.0.0
  emoji_picker_flutter: ^4.3.0
  file_picker: ^9.0.2
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.4.3
  flutter:
    sdk: flutter
  flutter_animated_button: ^2.0.4
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: 0.14.2

  flutter_local_notifications: ^19.0.0
  flutter_stripe: ^11.4.0
  flutter_tts: ^4.2.2
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  introduction_screen: ^3.1.14
  lottie: ^3.3.1
  open_file: ^3.5.10
  permission_handler: ^11.4.0
  printing: ^5.14.2
  provider: ^6.1.2
  #razorpay_flutter: ^1.4.0
  razorpay_flutter: ^1.4.0
  share_plus: ^10.1.4
  shared_preferences: ^2.4.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/crowd2.png"
  adaptive_icon_foreground: "assets/images/crowd2.png"
  adaptive_icon_background: "#ffffff"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/crowd2.png
    - assets/images/crowd1.png
    - assets/images/login.png
    - assets/images/person_placeholder.png
    - assets/images/img.png
    - assets/animations/s1.json
    - assets/animations/back.json
    - assets/animations/create.json
    - assets/animations/build.json
    - assets/animations/inspire.json
    - assets/animations/pay.json
    - assets/.env


  fonts:
        - family: Roboto
          fonts:
            - asset: assets/fonts/Roboto-Regular.ttf

